In [1]:
#CMU WORDLIST
import nltk
ntries=nltk.corpus.cmudict.entries()
len(ntries)

133737

In [2]:
ntries[:100]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [3]:
#3.wordnet
from nltk.corpus import wordnet as wn
wn.synsets('machine')

[Synset('machine.n.01'),
 Synset('machine.n.02'),
 Synset('machine.n.03'),
 Synset('machine.n.04'),
 Synset('machine.n.05'),
 Synset('car.n.01'),
 Synset('machine.v.01'),
 Synset('machine.v.02')]

In [4]:
wn.synset('car.n.01').lemma_names()

['car', 'auto', 'automobile', 'machine', 'motorcar']

In [5]:
#atask 2-sample text classifier
def gender_features(word):
    return{'last_letter':word[-1]}

In [6]:
gender_features('Obama')

{'last_letter': 'a'}

In [7]:
from nltk.corpus import names
labeled_names = ([(name, 'male') for name in names.words('male.txt')]+
[(name, 'female') for name in names.words('female.txt')])

In [8]:
import random
random.shuffle(labeled_names)

In [9]:
featuresets=[(gender_features(n),gender) for (n,gender) in labeled_names]

In [10]:
train_set,test_set=featuresets[500:],featuresets[:500]

In [11]:
import nltk
classifier=nltk.NaiveBayesClassifier.train(train_set)

In [13]:
classifier.classify(gender_features('keerthana'))

'female'

In [16]:
classifier.classify(gender_features('Nithin'))

'male'

In [17]:
classifier.classify(gender_features('Lakshmi'))


'female'

In [18]:
classifier.classify(gender_features('Dinesh'))

'female'

In [19]:
print(nltk.classify.accuracy(classifier,test_set))

0.7


In [20]:
#vectoriser and cosine siilarity
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
vect=CountVectorizer(binary=True)
corpus = ["Bugatti is all about French-style luxury and exceptional vehicles, but it’s a brand that stands for innovative technology, too  ", " Bugatti is in fact continuing a long-standing tradition here: the company founder Ettore Bugatti himself developed unique vehicles using groundbreaking technologies"]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [30]:
vocab=vect.vocabulary_

In [31]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

about:0
all:1
and:2
brand:3
bugatti:4
but:5
company:6
continuing:7
developed:8
ettore:9
exceptional:10
fact:11
for:12
founder:13
french:14
groundbreaking:15
here:16
himself:17
in:18
innovative:19
is:20
it:21
long:22
luxury:23
standing:24
stands:25
style:26
technologies:27
technology:28
that:29
the:30
too:31
tradition:32
unique:33
using:34
vehicles:35


In [33]:
print(vect.transform(["Bugatti is all about French-style luxury and exceptional vehicles, but it’s a brand that stands for innovative technology, too "]).toarray())

[[1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 1]]


In [34]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 1]
 [0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 1]]


In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
similarity = cosine_similarity(vect.transform(["LiFi is a wireless optical networking technology that uses LEDs for data transmission"]).toarray(), vect.transform([" LiFi is considered to be as a light-based WiFi which uses light instead of radio waves to transmit information."]).toarray())

In [37]:
similarity

array([[0.5]])